1645298134216
On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean

Everything up-to-date
1645301734216
On branch main
Your branch is up to date with 'origin/main'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   debug.log

no changes added to commit (use "git add" and/or "git commit -a")

Everything up-to-date
1645305334216
On branch main
Your branch is up to date with 'origin/main'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   debug.log

no changes added to commit (use "git add" and/or "git commit -a")

Everything up-to-date
1645308934216
On branch main
Your branch is up to date with 'origin/main'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   debug.log

no changes added to commit (use "git add" and/or "git commit -a")

Warning: Permanently added the ECDSA host key for IP address '140.82.114.4' to the list of known hosts.
Everything up-to-date
1645312534217
On branch main
Your branch is up to date with 'origin/main'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   debug.log

no changes added to commit (use "git add" and/or "git commit -a")

Everything up-to-date
1645316134216
On branch main
Your branch is up to date with 'origin/main'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   debug.log

no changes added to commit (use "git add" and/or "git commit -a")

Warning: Permanently added the ECDSA host key for IP address '140.82.113.3' to the list of known hosts.
Everything up-to-date
1645319734217
On branch main
Your branch is up to date with 'origin/main'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   debug.log

no changes added to commit (use "git add" and/or "git commit -a")

Warning: Permanently added the ECDSA host key for IP address '140.82.112.3' to the list of known hosts.
Everything up-to-date
1645323334217
On branch main
Your branch is up to date with 'origin/main'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   debug.log

no changes added to commit (use "git add" and/or "git commit -a")

Everything up-to-date
1645326934216
On branch main
Your branch is up to date with 'origin/main'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   debug.log

no changes added to commit (use "git add" and/or "git commit -a")

Everything up-to-date
1645330534217
On branch main
Your branch is up to date with 'origin/main'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   debug.log

no changes added to commit (use "git add" and/or "git commit -a")

Everything up-to-date
1645334134218
On branch main
Your branch is up to date with 'origin/main'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   debug.log

no changes added to commit (use "git add" and/or "git commit -a")

Everything up-to-date
1645337734218
On branch main
Your branch is up to date with 'origin/main'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   debug.log

no changes added to commit (use "git add" and/or "git commit -a")

Everything up-to-date
1645341334219
On branch main
Your branch is up to date with 'origin/main'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   debug.log

no changes added to commit (use "git add" and/or "git commit -a")

Everything up-to-date
1645344934218
On branch main
Your branch is up to date with 'origin/main'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   debug.log

no changes added to commit (use "git add" and/or "git commit -a")

Everything up-to-date
1645348534219
On branch main
Your branch is up to date with 'origin/main'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   debug.log

no changes added to commit (use "git add" and/or "git commit -a")

Everything up-to-date
1645352134220
On branch main
Your branch is up to date with 'origin/main'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   debug.log

no changes added to commit (use "git add" and/or "git commit -a")

Everything up-to-date
1645355734219
On branch main
Your branch is up to date with 'origin/main'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   debug.log

no changes added to commit (use "git add" and/or "git commit -a")

Everything up-to-date
1645359334220
On branch main
Your branch is up to date with 'origin/main'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   debug.log

no changes added to commit (use "git add" and/or "git commit -a")

Everything up-to-date
1645362934219
On branch main
Your branch is up to date with 'origin/main'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   debug.log

no changes added to commit (use "git add" and/or "git commit -a")

Everything up-to-date
1645366534220
On branch main
Your branch is up to date with 'origin/main'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   debug.log

no changes added to commit (use "git add" and/or "git commit -a")

Everything up-to-date
1645370134219
On branch main
Your branch is up to date with 'origin/main'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   debug.log

no changes added to commit (use "git add" and/or "git commit -a")

Everything up-to-date
1645373734220
On branch main
Your branch is up to date with 'origin/main'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   debug.log

no changes added to commit (use "git add" and/or "git commit -a")

Everything up-to-date
1645463011371
On branch main
Your branch is up to date with 'origin/main'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   debug.log
	modified:   waste_parse.js

no changes added to commit (use "git add" and/or "git commit -a")

Everything up-to-date
1645549411372
[main 94ae9bf] update
 1 file changed, 1 insertion(+), 1 deletion(-)

To github.com:edgecollective/wastewater-parse.git
   16bbfa4..94ae9bf  main -> main
1645635811371
On branch main
Your branch is up to date with 'origin/main'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   debug.log
	modified:   waste_parse.js

no changes added to commit (use "git add" and/or "git commit -a")

Everything up-to-date
1645722211371
[main 7e592bc] update
 1 file changed, 18 insertions(+), 9 deletions(-)

To github.com:edgecollective/wastewater-parse.git
   94ae9bf..7e592bc  main -> main
1645808611372
[main 7c22241] update
 1 file changed, 1 insertion(+), 1 deletion(-)

To github.com:edgecollective/wastewater-parse.git
   7e592bc..7c22241  main -> main
1645895011372
[main 842737f] update
 1 file changed, 1 insertion(+), 1 deletion(-)

To github.com:edgecollective/wastewater-parse.git
   7c22241..842737f  main -> main
1645981411372
On branch main
Your branch is up to date with 'origin/main'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   debug.log
	modified:   waste_parse.js

no changes added to commit (use "git add" and/or "git commit -a")

Everything up-to-date
1646067811372
On branch main
Your branch is up to date with 'origin/main'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   debug.log
	modified:   waste_parse.js

no changes added to commit (use "git add" and/or "git commit -a")

Everything up-to-date
1646154211372
On branch main
Your branch is up to date with 'origin/main'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   debug.log
	modified:   waste_parse.js

no changes added to commit (use "git add" and/or "git commit -a")

Everything up-to-date
1646170119146
Error: Command failed: ./grab.sh
To github.com:edgecollective/wastewater-parse.git
 ! [rejected]        main -> main (fetch first)
error: failed to push some refs to 'git@github.com:edgecollective/wastewater-parse.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

1646184517733
Error: Command failed: ./grab.sh
To github.com:edgecollective/wastewater-parse.git
 ! [rejected]        main -> main (fetch first)
error: failed to push some refs to 'git@github.com:edgecollective/wastewater-parse.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

1646198917030
Error: Command failed: ./grab.sh
To github.com:edgecollective/wastewater-parse.git
 ! [rejected]        main -> main (fetch first)
error: failed to push some refs to 'git@github.com:edgecollective/wastewater-parse.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

1646213317332
Error: Command failed: ./grab.sh
To github.com:edgecollective/wastewater-parse.git
 ! [rejected]        main -> main (fetch first)
error: failed to push some refs to 'git@github.com:edgecollective/wastewater-parse.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

1646227719646
Error: Command failed: ./grab.sh
To github.com:edgecollective/wastewater-parse.git
 ! [rejected]        main -> main (fetch first)
error: failed to push some refs to 'git@github.com:edgecollective/wastewater-parse.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

1646242118381
Error: Command failed: ./grab.sh
To github.com:edgecollective/wastewater-parse.git
 ! [rejected]        main -> main (fetch first)
error: failed to push some refs to 'git@github.com:edgecollective/wastewater-parse.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

1646256518232
Error: Command failed: ./grab.sh
To github.com:edgecollective/wastewater-parse.git
 ! [rejected]        main -> main (fetch first)
error: failed to push some refs to 'git@github.com:edgecollective/wastewater-parse.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

1646270917598
Error: Command failed: ./grab.sh
To github.com:edgecollective/wastewater-parse.git
 ! [rejected]        main -> main (fetch first)
error: failed to push some refs to 'git@github.com:edgecollective/wastewater-parse.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

1646285316740
Error: Command failed: ./grab.sh
To github.com:edgecollective/wastewater-parse.git
 ! [rejected]        main -> main (fetch first)
error: failed to push some refs to 'git@github.com:edgecollective/wastewater-parse.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

1646299717090
Error: Command failed: ./grab.sh
To github.com:edgecollective/wastewater-parse.git
 ! [rejected]        main -> main (fetch first)
error: failed to push some refs to 'git@github.com:edgecollective/wastewater-parse.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

1646314117894
Error: Command failed: ./grab.sh
To github.com:edgecollective/wastewater-parse.git
 ! [rejected]        main -> main (fetch first)
error: failed to push some refs to 'git@github.com:edgecollective/wastewater-parse.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

1646328517593
Error: Command failed: ./grab.sh
To github.com:edgecollective/wastewater-parse.git
 ! [rejected]        main -> main (fetch first)
error: failed to push some refs to 'git@github.com:edgecollective/wastewater-parse.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

1646342917996
Error: Command failed: ./grab.sh
To github.com:edgecollective/wastewater-parse.git
 ! [rejected]        main -> main (fetch first)
error: failed to push some refs to 'git@github.com:edgecollective/wastewater-parse.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

1646357317312
Error: Command failed: ./grab.sh
To github.com:edgecollective/wastewater-parse.git
 ! [rejected]        main -> main (fetch first)
error: failed to push some refs to 'git@github.com:edgecollective/wastewater-parse.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

1646371716688
Error: Command failed: ./grab.sh
To github.com:edgecollective/wastewater-parse.git
 ! [rejected]        main -> main (fetch first)
error: failed to push some refs to 'git@github.com:edgecollective/wastewater-parse.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

1646386117189
Error: Command failed: ./grab.sh
To github.com:edgecollective/wastewater-parse.git
 ! [rejected]        main -> main (fetch first)
error: failed to push some refs to 'git@github.com:edgecollective/wastewater-parse.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

1646400518435
Error: Command failed: ./grab.sh
To github.com:edgecollective/wastewater-parse.git
 ! [rejected]        main -> main (fetch first)
error: failed to push some refs to 'git@github.com:edgecollective/wastewater-parse.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

1646414917554
Error: Command failed: ./grab.sh
To github.com:edgecollective/wastewater-parse.git
 ! [rejected]        main -> main (fetch first)
error: failed to push some refs to 'git@github.com:edgecollective/wastewater-parse.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

1646431154974
On branch main
Your branch is up to date with 'origin/main'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   debug.log
	modified:   parse.py
	modified:   waste_parse.js

no changes added to commit (use "git add" and/or "git commit -a")

Everything up-to-date
1646445554975
On branch main
Your branch is up to date with 'origin/main'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   debug.log
	modified:   parse.py
	modified:   waste_parse.js

no changes added to commit (use "git add" and/or "git commit -a")

Everything up-to-date
1646459954975
On branch main
Your branch is up to date with 'origin/main'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   debug.log
	modified:   parse.py
	modified:   waste_parse.js

no changes added to commit (use "git add" and/or "git commit -a")

Everything up-to-date
1646474354976
On branch main
Your branch is up to date with 'origin/main'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   debug.log
	modified:   parse.py
	modified:   waste_parse.js

no changes added to commit (use "git add" and/or "git commit -a")

Everything up-to-date
1646488754975
On branch main
Your branch is up to date with 'origin/main'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   debug.log
	modified:   parse.py
	modified:   waste_parse.js

no changes added to commit (use "git add" and/or "git commit -a")

Everything up-to-date
1646503154976
[main be27c86] update
 1 file changed, 1 insertion(+), 1 deletion(-)

To github.com:edgecollective/wastewater-parse.git
   1acf08c..be27c86  main -> main
1646517554977
On branch main
Your branch is up to date with 'origin/main'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   debug.log
	modified:   parse.py
	modified:   waste_parse.js

no changes added to commit (use "git add" and/or "git commit -a")

Everything up-to-date
1646531954976
On branch main
Your branch is up to date with 'origin/main'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   debug.log
	modified:   parse.py
	modified:   waste_parse.js

no changes added to commit (use "git add" and/or "git commit -a")

Everything up-to-date
1646546354977
On branch main
Your branch is up to date with 'origin/main'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   debug.log
	modified:   parse.py
	modified:   waste_parse.js

no changes added to commit (use "git add" and/or "git commit -a")

Everything up-to-date
1646560754977
On branch main
Your branch is up to date with 'origin/main'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   debug.log
	modified:   parse.py
	modified:   waste_parse.js

no changes added to commit (use "git add" and/or "git commit -a")

Everything up-to-date
1646575154978
On branch main
Your branch is up to date with 'origin/main'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   debug.log
	modified:   parse.py
	modified:   waste_parse.js

no changes added to commit (use "git add" and/or "git commit -a")

Everything up-to-date
1646589554978
On branch main
Your branch is up to date with 'origin/main'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   debug.log
	modified:   parse.py
	modified:   waste_parse.js

no changes added to commit (use "git add" and/or "git commit -a")

Everything up-to-date
1646603954978
On branch main
Your branch is up to date with 'origin/main'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   debug.log
	modified:   parse.py
	modified:   waste_parse.js

no changes added to commit (use "git add" and/or "git commit -a")

Everything up-to-date
1646618354979
On branch main
Your branch is up to date with 'origin/main'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   debug.log
	modified:   parse.py
	modified:   waste_parse.js

no changes added to commit (use "git add" and/or "git commit -a")

Everything up-to-date
1646632754978
On branch main
Your branch is up to date with 'origin/main'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   debug.log
	modified:   parse.py
	modified:   waste_parse.js

no changes added to commit (use "git add" and/or "git commit -a")

Everything up-to-date
1646647154979
On branch main
Your branch is up to date with 'origin/main'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   debug.log
	modified:   parse.py
	modified:   waste_parse.js

no changes added to commit (use "git add" and/or "git commit -a")

Everything up-to-date
1646661554979
On branch main
Your branch is up to date with 'origin/main'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   debug.log
	modified:   parse.py
	modified:   waste_parse.js

no changes added to commit (use "git add" and/or "git commit -a")

Everything up-to-date
1646675954979
On branch main
Your branch is up to date with 'origin/main'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   debug.log
	modified:   parse.py
	modified:   waste_parse.js

no changes added to commit (use "git add" and/or "git commit -a")

Everything up-to-date
1646690354978
On branch main
Your branch is up to date with 'origin/main'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   debug.log
	modified:   parse.py
	modified:   waste_parse.js

no changes added to commit (use "git add" and/or "git commit -a")

Everything up-to-date
1646704754978
On branch main
Your branch is up to date with 'origin/main'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   debug.log
	modified:   parse.py
	modified:   waste_parse.js

no changes added to commit (use "git add" and/or "git commit -a")

Everything up-to-date
1646719154978
On branch main
Your branch is up to date with 'origin/main'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   debug.log
	modified:   parse.py
	modified:   waste_parse.js

no changes added to commit (use "git add" and/or "git commit -a")

Everything up-to-date
1646733554978
On branch main
Your branch is up to date with 'origin/main'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   debug.log
	modified:   parse.py
	modified:   waste_parse.js

no changes added to commit (use "git add" and/or "git commit -a")

Everything up-to-date
1646747954978
On branch main
Your branch is up to date with 'origin/main'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   debug.log
	modified:   parse.py
	modified:   waste_parse.js

no changes added to commit (use "git add" and/or "git commit -a")

Everything up-to-date
1646762354979
On branch main
Your branch is up to date with 'origin/main'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   debug.log
	modified:   parse.py
	modified:   waste_parse.js

no changes added to commit (use "git add" and/or "git commit -a")

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/arrays/datetimes.py", line 2211, in objects_to_datetime64ns
    values, tz_parsed = conversion.datetime_to_datetime64(data.ravel("K"))
  File "pandas/_libs/tslibs/conversion.pyx", line 360, in pandas._libs.tslibs.conversion.datetime_to_datetime64
TypeError: Unrecognized value type: <class 'str'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "parse.py", line 34, in <module>
    unixtime=pd.to_datetime(df.Date).astype(int) / 10**9
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/tools/datetimes.py", line 1051, in to_datetime
    values = convert_listlike(arg._values, format)
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/tools/datetimes.py", line 402, in _convert_listlike_datetimes
    result, tz_parsed = objects_to_datetime64ns(
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/arrays/datetimes.py", line 2217, in objects_to_datetime64ns
    raise err
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/arrays/datetimes.py", line 2199, in objects_to_datetime64ns
    result, tz_parsed = tslib.array_to_datetime(
  File "pandas/_libs/tslib.pyx", line 381, in pandas._libs.tslib.array_to_datetime
  File "pandas/_libs/tslib.pyx", line 613, in pandas._libs.tslib.array_to_datetime
  File "pandas/_libs/tslib.pyx", line 751, in pandas._libs.tslib._array_to_datetime_object
  File "pandas/_libs/tslib.pyx", line 742, in pandas._libs.tslib._array_to_datetime_object
  File "pandas/_libs/tslibs/parsing.pyx", line 281, in pandas._libs.tslibs.parsing.parse_datetime_string
  File "/usr/local/lib/python3.8/dist-packages/dateutil/parser/_parser.py", line 1368, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/dateutil/parser/_parser.py", line 643, in parse
    raise ParserError("Unknown string format: %s", timestr)
dateutil.parser._parser.ParserError: Unknown string format: 3/20/2022
3/21/2022
3/22/2022
3/23/2022
3/24/2022
3/25/2022
3/26/2022
3/27/2022
3/28/2022
3/29/2022
3/30/2022
3/31/2022
4/1/2022
4/2/2022
4/3/2022
4/4/2022
4/5/2022
4/6/2022
4/7/2022
4/8/2022
4/9/2022
4/10/2022
4/11/2022
4/12/2022
4/13/2022
4/14/2022
4/15/2022
4/16/2022
4/17/2022
4/18/2022
4/19/2022
4/20/2022
4/21/2022
4/22/2022
4/23/2022
4/24/2022
4/25/2022
4/26/2022
4/27/2022
4/28/2022
4/29/2022
4/30/2022
Everything up-to-date
1646776754979
On branch main
Your branch is up to date with 'origin/main'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   debug.log
	modified:   parse.py
	modified:   waste_parse.js

no changes added to commit (use "git add" and/or "git commit -a")

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/arrays/datetimes.py", line 2211, in objects_to_datetime64ns
    values, tz_parsed = conversion.datetime_to_datetime64(data.ravel("K"))
  File "pandas/_libs/tslibs/conversion.pyx", line 360, in pandas._libs.tslibs.conversion.datetime_to_datetime64
TypeError: Unrecognized value type: <class 'str'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "parse.py", line 34, in <module>
    unixtime=pd.to_datetime(df.Date).astype(int) / 10**9
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/tools/datetimes.py", line 1051, in to_datetime
    values = convert_listlike(arg._values, format)
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/tools/datetimes.py", line 402, in _convert_listlike_datetimes
    result, tz_parsed = objects_to_datetime64ns(
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/arrays/datetimes.py", line 2217, in objects_to_datetime64ns
    raise err
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/arrays/datetimes.py", line 2199, in objects_to_datetime64ns
    result, tz_parsed = tslib.array_to_datetime(
  File "pandas/_libs/tslib.pyx", line 381, in pandas._libs.tslib.array_to_datetime
  File "pandas/_libs/tslib.pyx", line 613, in pandas._libs.tslib.array_to_datetime
  File "pandas/_libs/tslib.pyx", line 751, in pandas._libs.tslib._array_to_datetime_object
  File "pandas/_libs/tslib.pyx", line 742, in pandas._libs.tslib._array_to_datetime_object
  File "pandas/_libs/tslibs/parsing.pyx", line 281, in pandas._libs.tslibs.parsing.parse_datetime_string
  File "/usr/local/lib/python3.8/dist-packages/dateutil/parser/_parser.py", line 1368, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/dateutil/parser/_parser.py", line 643, in parse
    raise ParserError("Unknown string format: %s", timestr)
dateutil.parser._parser.ParserError: Unknown string format: 3/20/2022
3/21/2022
3/22/2022
3/23/2022
3/24/2022
3/25/2022
3/26/2022
3/27/2022
3/28/2022
3/29/2022
3/30/2022
3/31/2022
4/1/2022
4/2/2022
4/3/2022
4/4/2022
4/5/2022
4/6/2022
4/7/2022
4/8/2022
4/9/2022
4/10/2022
4/11/2022
4/12/2022
4/13/2022
4/14/2022
4/15/2022
4/16/2022
4/17/2022
4/18/2022
4/19/2022
4/20/2022
4/21/2022
4/22/2022
4/23/2022
4/24/2022
4/25/2022
4/26/2022
4/27/2022
4/28/2022
4/29/2022
4/30/2022
Everything up-to-date
1646791154980
On branch main
Your branch is up to date with 'origin/main'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   debug.log
	modified:   parse.py
	modified:   waste_parse.js

no changes added to commit (use "git add" and/or "git commit -a")

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/arrays/datetimes.py", line 2211, in objects_to_datetime64ns
    values, tz_parsed = conversion.datetime_to_datetime64(data.ravel("K"))
  File "pandas/_libs/tslibs/conversion.pyx", line 360, in pandas._libs.tslibs.conversion.datetime_to_datetime64
TypeError: Unrecognized value type: <class 'str'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "parse.py", line 34, in <module>
    unixtime=pd.to_datetime(df.Date).astype(int) / 10**9
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/tools/datetimes.py", line 1051, in to_datetime
    values = convert_listlike(arg._values, format)
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/tools/datetimes.py", line 402, in _convert_listlike_datetimes
    result, tz_parsed = objects_to_datetime64ns(
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/arrays/datetimes.py", line 2217, in objects_to_datetime64ns
    raise err
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/arrays/datetimes.py", line 2199, in objects_to_datetime64ns
    result, tz_parsed = tslib.array_to_datetime(
  File "pandas/_libs/tslib.pyx", line 381, in pandas._libs.tslib.array_to_datetime
  File "pandas/_libs/tslib.pyx", line 613, in pandas._libs.tslib.array_to_datetime
  File "pandas/_libs/tslib.pyx", line 751, in pandas._libs.tslib._array_to_datetime_object
  File "pandas/_libs/tslib.pyx", line 742, in pandas._libs.tslib._array_to_datetime_object
  File "pandas/_libs/tslibs/parsing.pyx", line 281, in pandas._libs.tslibs.parsing.parse_datetime_string
  File "/usr/local/lib/python3.8/dist-packages/dateutil/parser/_parser.py", line 1368, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/dateutil/parser/_parser.py", line 643, in parse
    raise ParserError("Unknown string format: %s", timestr)
dateutil.parser._parser.ParserError: Unknown string format: 3/20/2022
3/21/2022
3/22/2022
3/23/2022
3/24/2022
3/25/2022
3/26/2022
3/27/2022
3/28/2022
3/29/2022
3/30/2022
3/31/2022
4/1/2022
4/2/2022
4/3/2022
4/4/2022
4/5/2022
4/6/2022
4/7/2022
4/8/2022
4/9/2022
4/10/2022
4/11/2022
4/12/2022
4/13/2022
4/14/2022
4/15/2022
4/16/2022
4/17/2022
4/18/2022
4/19/2022
4/20/2022
4/21/2022
4/22/2022
4/23/2022
4/24/2022
4/25/2022
4/26/2022
4/27/2022
4/28/2022
4/29/2022
4/30/2022
Everything up-to-date
1646805554980
On branch main
Your branch is up to date with 'origin/main'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   debug.log
	modified:   parse.py
	modified:   waste_parse.js

no changes added to commit (use "git add" and/or "git commit -a")

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/arrays/datetimes.py", line 2211, in objects_to_datetime64ns
    values, tz_parsed = conversion.datetime_to_datetime64(data.ravel("K"))
  File "pandas/_libs/tslibs/conversion.pyx", line 360, in pandas._libs.tslibs.conversion.datetime_to_datetime64
TypeError: Unrecognized value type: <class 'str'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "parse.py", line 34, in <module>
    unixtime=pd.to_datetime(df.Date).astype(int) / 10**9
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/tools/datetimes.py", line 1051, in to_datetime
    values = convert_listlike(arg._values, format)
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/tools/datetimes.py", line 402, in _convert_listlike_datetimes
    result, tz_parsed = objects_to_datetime64ns(
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/arrays/datetimes.py", line 2217, in objects_to_datetime64ns
    raise err
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/arrays/datetimes.py", line 2199, in objects_to_datetime64ns
    result, tz_parsed = tslib.array_to_datetime(
  File "pandas/_libs/tslib.pyx", line 381, in pandas._libs.tslib.array_to_datetime
  File "pandas/_libs/tslib.pyx", line 613, in pandas._libs.tslib.array_to_datetime
  File "pandas/_libs/tslib.pyx", line 751, in pandas._libs.tslib._array_to_datetime_object
  File "pandas/_libs/tslib.pyx", line 742, in pandas._libs.tslib._array_to_datetime_object
  File "pandas/_libs/tslibs/parsing.pyx", line 281, in pandas._libs.tslibs.parsing.parse_datetime_string
  File "/usr/local/lib/python3.8/dist-packages/dateutil/parser/_parser.py", line 1368, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/dateutil/parser/_parser.py", line 643, in parse
    raise ParserError("Unknown string format: %s", timestr)
dateutil.parser._parser.ParserError: Unknown string format: 3/20/2022
3/21/2022
3/22/2022
3/23/2022
3/24/2022
3/25/2022
3/26/2022
3/27/2022
3/28/2022
3/29/2022
3/30/2022
3/31/2022
4/1/2022
4/2/2022
4/3/2022
4/4/2022
4/5/2022
4/6/2022
4/7/2022
4/8/2022
4/9/2022
4/10/2022
4/11/2022
4/12/2022
4/13/2022
4/14/2022
4/15/2022
4/16/2022
4/17/2022
4/18/2022
4/19/2022
4/20/2022
4/21/2022
4/22/2022
4/23/2022
4/24/2022
4/25/2022
4/26/2022
4/27/2022
4/28/2022
4/29/2022
4/30/2022
Everything up-to-date
1646819954981
On branch main
Your branch is up to date with 'origin/main'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   debug.log
	modified:   parse.py
	modified:   waste_parse.js

no changes added to commit (use "git add" and/or "git commit -a")

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/arrays/datetimes.py", line 2211, in objects_to_datetime64ns
    values, tz_parsed = conversion.datetime_to_datetime64(data.ravel("K"))
  File "pandas/_libs/tslibs/conversion.pyx", line 360, in pandas._libs.tslibs.conversion.datetime_to_datetime64
TypeError: Unrecognized value type: <class 'str'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "parse.py", line 34, in <module>
    unixtime=pd.to_datetime(df.Date).astype(int) / 10**9
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/tools/datetimes.py", line 1051, in to_datetime
    values = convert_listlike(arg._values, format)
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/tools/datetimes.py", line 402, in _convert_listlike_datetimes
    result, tz_parsed = objects_to_datetime64ns(
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/arrays/datetimes.py", line 2217, in objects_to_datetime64ns
    raise err
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/arrays/datetimes.py", line 2199, in objects_to_datetime64ns
    result, tz_parsed = tslib.array_to_datetime(
  File "pandas/_libs/tslib.pyx", line 381, in pandas._libs.tslib.array_to_datetime
  File "pandas/_libs/tslib.pyx", line 613, in pandas._libs.tslib.array_to_datetime
  File "pandas/_libs/tslib.pyx", line 751, in pandas._libs.tslib._array_to_datetime_object
  File "pandas/_libs/tslib.pyx", line 742, in pandas._libs.tslib._array_to_datetime_object
  File "pandas/_libs/tslibs/parsing.pyx", line 281, in pandas._libs.tslibs.parsing.parse_datetime_string
  File "/usr/local/lib/python3.8/dist-packages/dateutil/parser/_parser.py", line 1368, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/dateutil/parser/_parser.py", line 643, in parse
    raise ParserError("Unknown string format: %s", timestr)
dateutil.parser._parser.ParserError: Unknown string format: 3/20/2022
3/21/2022
3/22/2022
3/23/2022
3/24/2022
3/25/2022
3/26/2022
3/27/2022
3/28/2022
3/29/2022
3/30/2022
3/31/2022
4/1/2022
4/2/2022
4/3/2022
4/4/2022
4/5/2022
4/6/2022
4/7/2022
4/8/2022
4/9/2022
4/10/2022
4/11/2022
4/12/2022
4/13/2022
4/14/2022
4/15/2022
4/16/2022
4/17/2022
4/18/2022
4/19/2022
4/20/2022
4/21/2022
4/22/2022
4/23/2022
4/24/2022
4/25/2022
4/26/2022
4/27/2022
4/28/2022
4/29/2022
4/30/2022
Everything up-to-date
1646834354982
On branch main
Your branch is up to date with 'origin/main'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   debug.log
	modified:   parse.py
	modified:   waste_parse.js

no changes added to commit (use "git add" and/or "git commit -a")

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/arrays/datetimes.py", line 2211, in objects_to_datetime64ns
    values, tz_parsed = conversion.datetime_to_datetime64(data.ravel("K"))
  File "pandas/_libs/tslibs/conversion.pyx", line 360, in pandas._libs.tslibs.conversion.datetime_to_datetime64
TypeError: Unrecognized value type: <class 'str'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "parse.py", line 34, in <module>
    unixtime=pd.to_datetime(df.Date).astype(int) / 10**9
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/tools/datetimes.py", line 1051, in to_datetime
    values = convert_listlike(arg._values, format)
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/tools/datetimes.py", line 402, in _convert_listlike_datetimes
    result, tz_parsed = objects_to_datetime64ns(
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/arrays/datetimes.py", line 2217, in objects_to_datetime64ns
    raise err
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/arrays/datetimes.py", line 2199, in objects_to_datetime64ns
    result, tz_parsed = tslib.array_to_datetime(
  File "pandas/_libs/tslib.pyx", line 381, in pandas._libs.tslib.array_to_datetime
  File "pandas/_libs/tslib.pyx", line 613, in pandas._libs.tslib.array_to_datetime
  File "pandas/_libs/tslib.pyx", line 751, in pandas._libs.tslib._array_to_datetime_object
  File "pandas/_libs/tslib.pyx", line 742, in pandas._libs.tslib._array_to_datetime_object
  File "pandas/_libs/tslibs/parsing.pyx", line 281, in pandas._libs.tslibs.parsing.parse_datetime_string
  File "/usr/local/lib/python3.8/dist-packages/dateutil/parser/_parser.py", line 1368, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/dateutil/parser/_parser.py", line 643, in parse
    raise ParserError("Unknown string format: %s", timestr)
dateutil.parser._parser.ParserError: Unknown string format: 3/20/2022
3/21/2022
3/22/2022
3/23/2022
3/24/2022
3/25/2022
3/26/2022
3/27/2022
3/28/2022
3/29/2022
3/30/2022
3/31/2022
4/1/2022
4/2/2022
4/3/2022
4/4/2022
4/5/2022
4/6/2022
4/7/2022
4/8/2022
4/9/2022
4/10/2022
4/11/2022
4/12/2022
4/13/2022
4/14/2022
4/15/2022
4/16/2022
4/17/2022
4/18/2022
4/19/2022
4/20/2022
4/21/2022
4/22/2022
4/23/2022
4/24/2022
4/25/2022
4/26/2022
4/27/2022
4/28/2022
4/29/2022
4/30/2022
Everything up-to-date
1646848754982
On branch main
Your branch is up to date with 'origin/main'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   debug.log
	modified:   parse.py
	modified:   waste_parse.js

no changes added to commit (use "git add" and/or "git commit -a")

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/arrays/datetimes.py", line 2211, in objects_to_datetime64ns
    values, tz_parsed = conversion.datetime_to_datetime64(data.ravel("K"))
  File "pandas/_libs/tslibs/conversion.pyx", line 360, in pandas._libs.tslibs.conversion.datetime_to_datetime64
TypeError: Unrecognized value type: <class 'str'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "parse.py", line 34, in <module>
    unixtime=pd.to_datetime(df.Date).astype(int) / 10**9
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/tools/datetimes.py", line 1051, in to_datetime
    values = convert_listlike(arg._values, format)
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/tools/datetimes.py", line 402, in _convert_listlike_datetimes
    result, tz_parsed = objects_to_datetime64ns(
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/arrays/datetimes.py", line 2217, in objects_to_datetime64ns
    raise err
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/arrays/datetimes.py", line 2199, in objects_to_datetime64ns
    result, tz_parsed = tslib.array_to_datetime(
  File "pandas/_libs/tslib.pyx", line 381, in pandas._libs.tslib.array_to_datetime
  File "pandas/_libs/tslib.pyx", line 613, in pandas._libs.tslib.array_to_datetime
  File "pandas/_libs/tslib.pyx", line 751, in pandas._libs.tslib._array_to_datetime_object
  File "pandas/_libs/tslib.pyx", line 742, in pandas._libs.tslib._array_to_datetime_object
  File "pandas/_libs/tslibs/parsing.pyx", line 281, in pandas._libs.tslibs.parsing.parse_datetime_string
  File "/usr/local/lib/python3.8/dist-packages/dateutil/parser/_parser.py", line 1368, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/dateutil/parser/_parser.py", line 643, in parse
    raise ParserError("Unknown string format: %s", timestr)
dateutil.parser._parser.ParserError: Unknown string format: 3/20/2022
3/21/2022
3/22/2022
3/23/2022
3/24/2022
3/25/2022
3/26/2022
3/27/2022
3/28/2022
3/29/2022
3/30/2022
3/31/2022
4/1/2022
4/2/2022
4/3/2022
4/4/2022
4/5/2022
4/6/2022
4/7/2022
4/8/2022
4/9/2022
4/10/2022
4/11/2022
4/12/2022
4/13/2022
4/14/2022
4/15/2022
4/16/2022
4/17/2022
4/18/2022
4/19/2022
4/20/2022
4/21/2022
4/22/2022
4/23/2022
4/24/2022
4/25/2022
4/26/2022
4/27/2022
4/28/2022
4/29/2022
4/30/2022
Everything up-to-date
1646863154983
On branch main
Your branch is up to date with 'origin/main'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   debug.log
	modified:   parse.py
	modified:   waste_parse.js

no changes added to commit (use "git add" and/or "git commit -a")

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/arrays/datetimes.py", line 2211, in objects_to_datetime64ns
    values, tz_parsed = conversion.datetime_to_datetime64(data.ravel("K"))
  File "pandas/_libs/tslibs/conversion.pyx", line 360, in pandas._libs.tslibs.conversion.datetime_to_datetime64
TypeError: Unrecognized value type: <class 'str'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "parse.py", line 34, in <module>
    unixtime=pd.to_datetime(df.Date).astype(int) / 10**9
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/tools/datetimes.py", line 1051, in to_datetime
    values = convert_listlike(arg._values, format)
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/tools/datetimes.py", line 402, in _convert_listlike_datetimes
    result, tz_parsed = objects_to_datetime64ns(
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/arrays/datetimes.py", line 2217, in objects_to_datetime64ns
    raise err
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/arrays/datetimes.py", line 2199, in objects_to_datetime64ns
    result, tz_parsed = tslib.array_to_datetime(
  File "pandas/_libs/tslib.pyx", line 381, in pandas._libs.tslib.array_to_datetime
  File "pandas/_libs/tslib.pyx", line 613, in pandas._libs.tslib.array_to_datetime
  File "pandas/_libs/tslib.pyx", line 751, in pandas._libs.tslib._array_to_datetime_object
  File "pandas/_libs/tslib.pyx", line 742, in pandas._libs.tslib._array_to_datetime_object
  File "pandas/_libs/tslibs/parsing.pyx", line 281, in pandas._libs.tslibs.parsing.parse_datetime_string
  File "/usr/local/lib/python3.8/dist-packages/dateutil/parser/_parser.py", line 1368, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/dateutil/parser/_parser.py", line 643, in parse
    raise ParserError("Unknown string format: %s", timestr)
dateutil.parser._parser.ParserError: Unknown string format: 3/20/2022
3/21/2022
3/22/2022
3/23/2022
3/24/2022
3/25/2022
3/26/2022
3/27/2022
3/28/2022
3/29/2022
3/30/2022
3/31/2022
4/1/2022
4/2/2022
4/3/2022
4/4/2022
4/5/2022
4/6/2022
4/7/2022
4/8/2022
4/9/2022
4/10/2022
4/11/2022
4/12/2022
4/13/2022
4/14/2022
4/15/2022
4/16/2022
4/17/2022
4/18/2022
4/19/2022
4/20/2022
4/21/2022
4/22/2022
4/23/2022
4/24/2022
4/25/2022
4/26/2022
4/27/2022
4/28/2022
4/29/2022
4/30/2022
Everything up-to-date
